version: '2'

services:
    db:
        image: mysql
        volumes:
            - ./.data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    php:
        build: php/prod
        volumes:
            - ../app:/var/www/istsi
            - ../cache:/var/www/cache
            - ../logs:/var/www/logs
            - ../data:/var/www/data
    nginx:
        build: nginx/staging
        ports:
            - 443:443
        volumes_from:
            - php
        volumes:
            - ../logs/nginx/:/var/log/nginx